### ISSUE TITLE
Add support for two-factor github auth

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman-studio#15]
If users have enabled two factor auth in github, then basic auth will fail.  Documentation found here:

https://developer.github.com/v3/auth/#working-with-two-factor-authentication

**Comment by msavy** [comment]
[HubPress](https://github.com/HubPress/hubpress.io) is a JS-based blogging platform for GH which I’ve been trying out lately for my personal blog. They handle this exact problem, so might be worth checking out their solution.

The pattern is that you log in with your normal username/password, and then it bumps you back to the logon page to try again with an additional token field.

Example:

![image](https://cloud.githubusercontent.com/assets/423513/19409956/29658e3a-92d8-11e6-91f5-dd1db1456cdc.png)

(Correct credentials but require 2FA):

![image](https://cloud.githubusercontent.com/assets/423513/19409984/89e426ae-92d8-11e6-8550-9b94442011e3.png)

A little message (not shown) briefly shows up saying 2FA is required.

Seems a reasonably nice pattern, but perhaps could be improved on.
