### ISSUE TITLE
Consider using Yarn?

### ISSUE THREAD

**Issue by msavy** [apiman/apiman-studio#18]
https://yarnpkg.com/

It's a project from Google, Facebook and co to  provide a much more reliable experience for JS package resolution and reproducibility. In particular it seems to handle dependency locking in a more sensible way (e.g. updating its lock file when you update and add deps rather than waiting for you to do it manually). 

Furthermore it claims to be much faster and have caching that actually works properly.

Yes... new week, new JS project; this seems worth checking out, though.

**Comment by kahboom** [comment]
Yeah this is being used in another project at RH. I've heard good things about it but haven't checked it out in depth.

**Comment by msavy** [comment]
I gave it a quick test out yesterday. Seems to work well. To migrate you just type `yarn` and it seems to be able to figure everything out.

**Comment by EricWittmann** [comment]
Cool - and thanks for opening an Issue for this so we don't lose track of it.  We should do that more often for stuff like this.

**Comment by msavy** [comment]
Just to update. Yarn works without hitch and is much quicker to resolve deps (10s vs 40s on my machine) - it produces a dependency lock file which can (and should) be added to the repo to ensure everyone is using the same deps and transitives. 

Yarn uses the same backend as node, and is [pretty much a drop-in replacement](https://yarnpkg.com/en/docs/migrating-from-npm), but it behaves better.

It also works properly in offline environments without needing proxy hacks https://yarnpkg.com/blog/2016/11/24/offline-mirror/ which should be useful for prod.

I don't think there's any rush to move over, but just providing some additional information as I've gained a bit more experience using it.

**Comment by kahboom** [comment]
Just wanted to comment on here and say that I've had a positive experience with Yarn and recommend switching over (obviously not sure what the priorities are). Then again I never had night terrors with NPM either, except for the offline proxy hassle, transitional errors, and crappy shrinkwrapping- all of which Yarn seem to solve. It also works well with angular-cli, which is great for getting AOT and lazy loading to play well together. Would be happy to help if it's decided to go that route.

**Comment by EricWittmann** [comment]
Done! :)
