### ISSUE TITLE
Don't store passwords in the clear!

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman-studio#24]
Any time a password is stored, even though we're currently storing them in browser local/session storage, they should still not be in the clear.  They should at least be obfuscated.

**Comment by msavy** [comment]
Thought - can the token not be stored rather than the password? https://github.com/blog/1509-personal-api-tokens

Avoiding storing it altogether seems even better than trying to ensure you never leak it.

**Comment by EricWittmann** [comment]
We're already using tokens.  It's been awhile since I wrote the login stuff - I'll need to review it before I consider how we can be more secure.  

In the long run we'll have a back-end which will allow us to properly implement OAuth web flows and then we'll never even know the password.

**Comment by EricWittmann** [comment]
See https://github.com/apiman/apiman-studio/issues/48
