### ISSUE TITLE
Improve the "Loading" screen

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman-studio#31]
The loading screen is what the user sees when the application is initially loading.  The markup for this is found in the host/index page and should be improved (currently it's just "Loading..." text!).

**Comment by msavy** [comment]
I've been playing around and (trying to _start_ getting up-to-date with the new CSS animation stuff). Hope I might be able to contribute something fun!

Here's a first little prototype idea, hopefully do something fancier shortly.

The idea is that apiman fades in on load, then fades out as/when load completes (or similar). It uses pure HTML & CSS but I'd imagine a bit of JS might be necessary for real the implementation. 

![image](https://i.imgur.com/QyMGIL2.gifv)

**Comment by msavy** [comment]
Here's a codepen (animations seem smoother in chrome FWIW). 

https://codepen.io/marcsavy/pen/WRmMmy

**Comment by EricWittmann** [comment]
Oh that's very nice!  PR forthcoming?  :)

**Comment by msavy** [comment]
I'd be very glad to if you think it looks good enough!

**Comment by msavy** [comment]
BTW, I hacked the SVG in Inscape for that presentation I did at JBCNConf, and I'm no pro with it, so it's probably slightly wonky - hah.

**Comment by msavy** [comment]
How's about this one for April 1st ;-) 

https://codepen.io/marcsavy/pen/MJxXYQ

**Comment by msavy** [comment]
I'm nearly ready to make a PR for you to preview. One small thing, which do you prefer:

Unmodified:
<img src="https://cloud.githubusercontent.com/assets/423513/22996441/b19f3716-f3c6-11e6-98d0-38925da76cc4.png" width=50%>

With `border-radius: 10%`:
<img src="https://cloud.githubusercontent.com/assets/423513/22996406/8d20e40c-f3c6-11e6-9fb7-94f052be636e.png" width=50%>

More extreme (50%)

<img src="https://cloud.githubusercontent.com/assets/423513/22996835/0f39fa2c-f3c8-11e6-9e41-a167ac54dbb7.png" width=50%>




Here's a codepen: NB: I set a darker background to make it easier to design, but in reality it's a lighter colour to match the normal UI background colour as you can see in the pics. Any weirdness with corner rounding can be fixed relatively easily, I think - just gauging what you think. 

https://codepen.io/marcsavy/pen/ggEEoK

**Comment by EricWittmann** [comment]
I like the 10% one.  Looks nice!

**Comment by msavy** [comment]
@EricWittmann OK, thoughts

![image](https://cloud.githubusercontent.com/assets/423513/23043009/cbbd099e-f492-11e6-84a1-cb1a36652cee.png)


![image](https://cloud.githubusercontent.com/assets/423513/23042969/ad567990-f492-11e6-8cee-dbaa01b625a6.png)

Can make them available for you to pull and see what you think.

**Comment by EricWittmann** [comment]
Oh I like the one with the borders/outline!

**Comment by msavy** [comment]
Closed via https://github.com/apiman/apiman-studio/pull/40

**Comment by EricWittmann** [comment]
Looks great, thanks for this. :)

**Comment by msavy** [comment]
My pleasure.  Hope to get involved with something more substantial soon.
