### ISSUE TITLE
doc reference link doesn't exist

### ISSUE THREAD

**Issue by hodrigohamalho** [apiman/apiman-studio#77]
http://studio.apiman.io/

**Comment by EricWittmann** [comment]
I just noticed this myself on Friday. :)

Where, specifically, did you notice this link (making sure I track down all the stale references)?

**Comment by hodrigohamalho** [comment]
1) http://www.apidesigner.org/download/
2) https://github.com/apiman/apiman-studio/blob/master/README.md

**Comment by EricWittmann** [comment]
I think these are all fixed up now.  Thanks for the report. :)

**Comment by hodrigohamalho** [comment]
Just to know, What was wrong ?

**Comment by EricWittmann** [comment]
I changed the project website from "studio.apiman.io" to "www.apidesigner.org".  We're still working on final project branding (name, logo, etc) for this, so it may change again!

**Comment by EricWittmann** [comment]
So there were some stale references to the old project website that I hadn't fixed up (after the domain name was changed). :)

**Comment by hodrigohamalho** [comment]
Nice Eric!
